run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - .git
    - .github

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - gosec
    - ineffassign
    - unconvert
    - gofumpt
    - goimports
    - misspell
    - unparam
    - prealloc
    - bodyclose
    - gocritic
  disable:
    - unused
    - deadcode
    - structcheck
    - varcheck

linters-settings:
  govet:
    check-shadowing: true
  revive:
    confidence: 0.8
  gosec:
    severity: medium
    confidence: medium
  gofumpt:
    extra-rules: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck