version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unconvert
    - misspell
    - unparam
    - bodyclose
  disable:
    - revive
    - gocritic
    - prealloc
    - gosec

linters-settings:
  govet:
    enable:
      - shadow
  revive:
    confidence: 0.8
  gosec:
    severity: medium
    confidence: medium

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
    - .git
    - .github
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - path: pkg/parser/ports.go
      linters:
        - gosec
      text: "G115: integer overflow conversion"