run:
  timeout: 3m
  issues-exit-code: 1
  tests: true

linters-settings:
  gofumpt:
    module-path: github.com/lucchesi-sec/portscan
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: error-naming
      - name: exported
        arguments: ["checkPrivateReceivers"]
      - name: indent-error-flow
      - name: var-naming
  gocyclo:
    min-complexity: 20
  govet:
    check-shadowing: true

linters:
  enable:
    - govet
    - staticcheck
    - gofumpt
    - goimports
    - revive
    - gocyclo
    - misspell
    - nilerr
    - prealloc
  disable:
    - errcheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test.go
      linters:
        - gocyclo
