name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          
      - name: Install linters
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          go install mvdan.cc/gofumpt@latest
          go install golang.org/x/tools/cmd/goimports@latest
          
      - name: Run linters
        run: |
          golangci-lint run ./...
          
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ['1.23', '1.24']
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          
      - name: Run tests
        run: go test -v -race ./...
        
      - name: Run benchmarks
        shell: bash
        run: |
          if [ -f "./internal/core/"*_test.go ]; then
            go test -bench=. ./internal/core -run=^$
          else
            echo "No test files found in internal/core, skipping benchmarks"
          fi
        
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          
      - name: Run security checks
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          go install golang.org/x/vuln/cmd/govulncheck@latest
          gosec ./...
          govulncheck ./...
          
  build:
    runs-on: ubuntu-latest
    needs: [lint, test, security]
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          
      - name: Build binary
        run: make build
        
      - name: Test binary
        run: ./bin/portscan version
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: portscan-dev-build
          path: bin/portscan
          retention-days: 7