name: Documentation

on:
  push:
    branches: [main]
    paths:
      - '**.go'
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [main]
    paths:
      - '**.go'
      - 'docs/**'
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install documentation tools
      run: |
        # Install PlantUML
        sudo apt-get update
        sudo apt-get install -y plantuml graphviz

        # Install Node.js tools
        npm install -g @mermaid-js/mermaid-cli markdownlint-cli

        # Install Go documentation tools
        go install golang.org/x/tools/cmd/godoc@latest
        go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest

    - name: Generate code documentation
      run: |
        # Generate documentation from code
        go run scripts/generate-docs.go -src . -out docs/generated -format markdown

        # Generate API documentation
        gomarkdoc --output docs/api/ ./...

    - name: Generate architecture diagrams
      working-directory: docs/architecture
      run: |
        make diagrams

    - name: Validate documentation
      working-directory: docs/architecture
      run: |
        make validate

    - name: Generate documentation statistics
      working-directory: docs/architecture
      run: |
        make stats > ../../docs/generated/stats.txt

    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: |
          docs/generated/
          docs/api/

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages

  check-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check markdown links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        folder-path: 'docs/'

  spell-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Spell check
      uses: streetsidesoftware/cspell-action@v5
      with:
        files: |
          docs/**/*.md
          *.md
